apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: inventario

data:
  SQL_API_URL: "http://api-sql-service"
  MONGO_API_URL: "http://api-mongo-service"
  LDAP_SERVER: "ldap://192.168.1.100"
